---
title: "FinFlexMacro"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(jsonlite)
library(dplyr)
library(tidyr)
```

```{r data-create, echo = F}
intDat <- read.csv('intDat.csv', header = TRUE, stringsAsFactors = FALSE)
names(intDat) <- c("date", "1 month",
                   "2 month", "3 month",
                   "6 month", "1 year",
                   "2 year", "3 year",
                   "5 year", "7 year",
                   "10 year", "20 year",
                   "30 year")

intDat[intDat == "N/A"] <- NA
## organize data to long format
intDat <- intDat %>% gather(x, y, -date)
intDat <- intDat %>% separate(date, "/", into = c('month', 'day', 'year'), remove = FALSE) %>% mutate(year = ifelse(as.numeric(year) <= 19, paste("20", year, sep = ""),
                                                                                                                    paste("19", year, sep = ""))) %>%
  mutate(date = paste(month, day, year, sep = "/"))
```

```{r, echo = F, results = 'asis'}
cat('<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>')
cat('<script src="selectize.js"></script>')
cat(
  paste(
  '<script>
    var data = ',toJSON(intDat),';
  </script>'
  , sep="")
)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Yield Curve Data

```{r, echo = FALSE, results = 'asis'}
myDiv <- cat('<div id = "widget-area" style = "display:flex;"><div id = "plot-div" style="width:80%; height:400px;"></div>')
options <- paste("<option value ='", unique(intDat$date), "'>", unique(intDat$date), "</option>", sep = "")
cat("<div style = 'text-align:center'><h5>Select the day(s):</h5>")
cat(paste("<select id = 'select-day' style = 'align:center;'>", paste(options, collapse = ""),
          "</select>"))
cat('</div></div>')
## make the plot change when the select changes:
cat(paste("<script>
$('#select-day').selectize({maxItems:8, theme: 'links'});
$('#select-day-selectized').css('min-width', '60px');
Plotly.plot('plot-div', [], {margin: {
t: 40, //top margin
l: 50, //left margin
r: 20, //right margin
b: 100 //bottom margin
}, yaxis: {range: [0, 10]}}, {displayModeBar: false});
$('#select-day').on('change', function() {
  var subDatX = [];
  var subDatY = [];
  var currVal = $('#select-day').val();
  var traces = [];
  if (currVal != null)
  {
  for (var i = 0; i < currVal.length; i++)
  {
    for (var j = 0; j < data.length; j++)
    {
      if (data[j].date == currVal[i])
      {
        subDatX.push(data[j].x);
        subDatY.push(data[j].y);
      }
    }
    temp = {};
    temp.x = subDatX;
    temp.y = subDatY;
    temp.type = 'scatter';
    temp.name = 'date: ' + currVal[i];
    traces.push(temp);
    subDatX = [];
    subDatY = [];
  }
  // Create the plotly plot
  var plotDat = traces;
  } else {
    var plotDat = [];
  }
  var layout = {margin: {
t: 40, //top margin
l: 50, //left margin
r: 20, //right margin
b: 100 //bottom margin
},
title: '',
xaxis: {title: 'Term'},
yaxis: {title: 'Rate'}};
  Plotly.newPlot('plot-div', plotDat, layout, {displayModeBar: false});
});</script>"))

```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

